### ISSUE TITLE
Add explicit MIT License to source dist

### ISSUE THREAD

**Issue by pmlandwehr** [jaraco/tempora#1]
Hey-lo,

I'm building a version of `tempora` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires an actual license file be bundled with the build and (usually) that said license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution.

Would you consider adding a full copy of the MIT License to the bundle, along with an appropriate manifest?

**Comment by jaraco** [comment]
Hi. Per jaraco/skeleton#1, I avoid bundling a license file. I recommend that the builder recipe for conda-forge could rely on the license declared in the metadata either to bundle the license at build time or to rely simply on the license declaration in the package metadata.

**Comment by jakirkham** [comment]
We do relay license metadata to end users, but we have found that not everyone is satisfied by this approach. In particular, we have had representatives from companies that are fairly prickly about licenses complain we have no license file. Maybe this would be easier if we had some way to address this on the `setuptools` end? ( https://github.com/pypa/setuptools/issues/357 )

In the interim, what if we provide you a PR with the license file and add it to the MANIFEST.in? Would you accept it?

**Comment by jaraco** [comment]
I don't feel the Setuptools solution is helpful as it still requires copying the license file duplicately with making the license declaration. It's lots of needless redundancy and potential for deviation. I wish for it to be as simple as selecting a well-known reference for common licenses.

Perhaps these companies should be less prickly where there's been no demonstrated risk by metadata referencing a license.

Perhaps the licenses should be adapted to be more readily applicable via a reference.

Or perhaps as suggested in skeleton#1, the community could put together a standard that doesn't involve all the work of including

**Comment by jaraco** [comment]
A PR isn't really helpful because I still have to cut a release.

Perhaps I should just concede and adopt the clumsy, duplicative convention that others have adopted, but that would require an update to the skeleton, and then merged of the skeleton with the projects, then new releases. It's a substantial undertaking for something that honestly feels like a waste of my time.

That's why I wish to rely on the best available declarative license until a better, non-duplicative paradigm emerges.
