### ISSUE TITLE
Release 2.1.1 on PyPI

### ISSUE THREAD

**Issue by sbraz** [jaraco/tempora#13]
Hi Jason,
I'm not sure which one of the CI builds failed to release it but 2.1.1 isn't on PyPI. Can you please upload it?

**Comment by sbraz** [comment]
Hi @jaraco, have you seen this issue?

**Comment by jaraco** [comment]
I hadn’t seen it yet. I’ll take a look tomorrow or this weekend

**Comment by jaraco** [comment]
Turns out the Azure pipelines weren't authorized to run. Now they have and the tag is published. Thanks for bringing it to my attention.
