### ISSUE TITLE
incomplete jaraco.functools removal

### ISSUE THREAD

**Issue by nekopsykose** [jaraco/tempora#21]
5.2.0 says jaraco.functools was removed (https://github.com/jaraco/tempora/commit/6485c745091860d1f85d31d70d63b90f2be6acae), but timing.py still imports it

**Comment by jaraco** [comment]
oops!

**Comment by jaraco** [comment]
Annoying that tests didn't catch that, but that's part of the problem with masked dependencies... sometimes dependencies for the tests will satisfy unspecified dependencies on the package.

Thanks for reporting the issue.

**Comment by nekopsykose** [comment]
no worries. thanks for the fix!
