### ISSUE TITLE
RFE: use `zoneinfo` instead of `pytz`

### ISSUE THREAD

**Issue by kloczek** [jaraco/tempora#29]
Switch to standard `zoneinfo` module.
Below may help  https://github.com/pydantic/pydantic-core/commit/fd262933

**Comment by jaraco** [comment]
Today I tried using GitHub Copilot to enact this change. It was a disaster. It understood the basic concept of porting from pytz to zoneinfo and also understood that one could use `backports.zoneinfo` on Python 3.8, but it did not understand the code and made incorrect changes like:

```diff
@@ -97,9 +100,7 @@
         Rely on pytz.localize to ensure new result honors DST.
         """
         try:
-            tz = dt.tzinfo
-            return tz.localize(dt.replace(tzinfo=None))
-        except AttributeError:
+            return dt.astimezone(dt.tzinfo)
         except AttributeError:
             return dt
 ```

Moreover, the diff it provided wouldn't apply to the source. In its first render, it provided the whole output of the file that I could have copy/pasted over the original code, but in later iterations, it only gave me snippets (with comments indicating that it was unchanged). That kind of output isn't very helpful, as it requires me to tediously apply the changes to the code (and make my own mistakes). Overall, Copilot was helpful in giving me a hint about what needs to be done, but ultimately, I'm responsible for making the meaningful changes.

**Comment by jaraco** [comment]
I've started work in #30, but one of the tests is failing. I believe it may be revealing a bug in zoneinfo.

**Comment by jaraco** [comment]
Indeed, zoneinfo gives an incorrect result for the duration between two days that cross a DST boundary:

```
 ~ @ py
Python 3.13.0b2 experimental free-threading build (tags/v3.13.0b2:3a83b172af, Jun 16 2024, 16:15:00) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zoneinfo
>>> import datetime
>>> datetime.datetime(2018, 3, 11, 9, 0, 0, tzinfo=zoneinfo.ZoneInfo('US/Eastern')) - datetime.datetime(2018, 3, 10, 9, 0, 0, tzinfo=zoneinfo.ZoneInfo('US/Eastern'))
datetime.timedelta(days=1)
```

The correct answer should be 23 hours.

However, pytz doesn't produce the correct answer either when comparing two such dates:

```
 ~ @ pip-run pytz
Python 3.13.0b2 experimental free-threading build (tags/v3.13.0b2:3a83b172af, Jun 16 2024, 16:15:00) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytz
>>> import datetime
>>> datetime.datetime(2018, 3, 11, 9, 0, 0, tzinfo=pytz.timezone('US/Eastern')) - datetime.datetime(2018, 3, 10, 9, 0, 0, tzinfo=pytz.timezone('U\
S/Eastern'))
datetime.timedelta(days=1)
```

It does, however, return the correct values when using localize:

```
 ~ @ pip-run pytz -- -q
>>> import pytz
>>> import datetime
>>> est = pytz.timezone('US/Eastern')
>>> est.localize(datetime.datetime(2018, 3, 11, 9, 0, 0)) - est.localize(datetime.datetime(2018, 3, 10, 9, 0, 0))
datetime.timedelta(seconds=82800)
```

**Comment by jaraco** [comment]
[This answer](https://stackoverflow.com/a/43127752/70170) seems to indicate that it should be possible to simply replace `.localize` with `.replace`, but I've thusfar been unable to create a reliable timedelta from two dates that cross a DST boundary without `pytz.localize` (https://gist.github.com/jaraco/624a01514f34159315b42ad62d870d7e).

**Comment by jaraco** [comment]
The localize function seems to be performing some adjustments based on the date to which it's applied:

```
>>> import pytz
>>> import datetime
>>> est = pytz.timezone('US/Eastern')
>>> est.localize(datetime.datetime(2018, 3, 11, 9, 0, 0))
datetime.datetime(2018, 3, 11, 9, 0, tzinfo=<DstTzInfo 'US/Eastern' EDT-1 day, 20:00:00 DST>)
>>> est.localize(datetime.datetime(2018, 3, 10, 9, 0, 0))
datetime.datetime(2018, 3, 10, 9, 0, tzinfo=<DstTzInfo 'US/Eastern' EST-1 day, 19:00:00 STD>)
```

**Comment by jaraco** [comment]
There's more info in the Gotcha! section of [this blog](https://engineering.backmarket.com/moving-forward-in-pythons-time-and-time-zones-aa3ccbd4569a). Apparently, to do arithmetic for absolute time, the times need to be converted to UTC first. That means the design is going to need to be revisited.

**Comment by jaraco** [comment]
The test that is failing was added in #5. I'm not confident the test adequately captured the actual missed expectation. Maybe it's okay that two times 23 hours apart return a `timedelta(days=1)` when compared.

In #30 (and particularly in e807db27d42eac8f0b77c71c1c60dc9569760fb1), I'm basically removing that expectation and replacing it with new expectations about when the command is due (5eb938fd1fcad3d1688fca40faca355396fa7510).

**Comment by kloczek** [comment]
Please use instead try except something like below
```python
if sys.version_info >= (3, 9):
    foo
else
    bar
```
To allow in the future automatically drop legacy code using `pyupgrade'.
