### ISSUE TITLE
1 test fails on Fedora

### ISSUE THREAD

**Issue by radez** [jaraco/tempora#7]
This is being run on Fedora 31 with Python3.
not sure how long this log will exist, but here's the link to the rpm build log that executes the test.
https://kojipkgs.fedoraproject.org//work/tasks/2362/34112362/build.log

+ /usr/bin/python3 -m pytest --ignore=build
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.3.1, py-1.7.0, pluggy-0.8.1
rootdir: /builddir/build/BUILD/tempora-1.14, inifile: pytest.ini
plugins: flake8-1.0.1
collected 25 items
tempora/__init__.py ..........F                                          [ 44%]
tempora/timing.py ...                                                    [ 56%]
tempora/utc.py .                                                         [ 60%]
tempora/tests/test_schedule.py ........                                  [ 92%]
tests/test_timing.py ..                                                  [100%]
=================================== FAILURES ===================================
______________________ [doctest] tempora.parse_timedelta _______________________
432 
433 	>>> parse_timedelta('1 year, 1 month')
434 	datetime.timedelta(days=395, seconds=58685)
435 
436 	Note that months and years strict intervals, not aligned
437 	to a calendar:
438 
439 	>>> now = datetime.datetime.now()
440 	>>> later = now + parse_timedelta('1 year')
441 	>>> later.replace(year=now.year) - now
Expected:
    datetime.timedelta(seconds=20940)
Got:
    datetime.timedelta(days=-1, seconds=20940)
/builddir/build/BUILD/tempora-1.14/tempora/__init__.py:441: DocTestFailure
===================== 1 failed, 24 passed in 2.41 seconds ======================

**Comment by jaraco** [comment]
Gah. I’ll bet that test fails everywhere. I’m pretty sure the leap day next Feb 29 is what breaks the test.

**Comment by jaraco** [comment]
[confirmed](https://travis-ci.org/jaraco/tempora/builds/519058649)

**Comment by radez** [comment]
Thx for the quick fix!
